import { mount } from "svelte";
import "./view-fixture";
import { applyTheme } from "./themes";
applyTheme(new URLSearchParams(location.search).get("theme"));
import { promptTitles } from "$lib/plugins/trace/prompt-titles.svelte";
import ViewHarness from "./ViewHarness.svelte";
const errors: string[] = [];
window.addEventListener("error", (event) => errors.push(event.message));
window.addEventListener("unhandledrejection", (event) => errors.push(String(event.reason)));
const application = mount(ViewHarness, { target: document.querySelector("#app")! }) as { harness: Record<string, unknown> };
(window as any).trace = { ...application.harness, errors, configureTitles: (settings: Record<string, unknown> = {}) => promptTitles.configure(settings) };
